### ISSUE TITLE
^P Message bug

### ISSUE THREAD

**Issue by gurrhack** [gurrhack/NetHack-Android#11]
Reported by Travis Thibeau
"there is a bug that when I control p for last message it skips the LAST message and goes to the one before leaving me message blind."

**Comment by h-jani** [comment]
It only skips a message if that last message was hidden because the user has moved a square, etc., it works as expected when it disappeared because an other message entered the window.
I think this is the default behavior in "vanilla" NetHack 3.4.3 too, when using the option `msg_window:single`.

**Comment by gurrhack** [comment]
I will change this for the next (major) release so that control p will open a window with the entire history, instead of rewinding one line at a time.

**Comment by gurrhack** [comment]
Fixed
