### ISSUE TITLE
Loading custom tiles doesn't always work

### ISSUE THREAD

**Issue by gurrhack** [gurrhack/NetHack-Android#13]
Browsing for a custom tileset will sometimes return a "virtual" path to the file which will subsequently fail to load.

Found on reddit, reported by curtmack: "You need to use your file browser to get the path all the way from the root of your storage device to the downloads folder where you saved it. When you go straight to your downloads folder it gets an alias and the NetHack app won't load it."

I'd appreciate if anyone reading this can explain how to reproduce this bug because I can't do it on any of my devices.

**Comment by pftbest** [comment]
I do not know if it's related, but I've made a screencast of what happens on my nexus5 when I select image using default file picker.
19MiB mp4 video:
https://googledrive.com/host/0B4ouTzM6vLORflJYVGZHUzk2VTZpRW1KUzh5VEhOWXNGVlBlbjBRYlZzcEJBTzNkWFpneVE/demo.mp4

**Comment by pftbest** [comment]
Also since Android 6 storage is adoptable[1], so fully qualified path can dynamically change at any time.
A better design would be to save a copy of an image to a known location, in the nethack folder for example. And then use getExternalFilesDir API instead of a fixed path.

**Comment by gurrhack** [comment]
Yes, that makes sense.

**Comment by gurrhack** [comment]
Fixed
