### ISSUE TITLE
Update to Nethack 3.6.0

### ISSUE THREAD

**Issue by Ranbato** [gurrhack/NetHack-Android#14]
Woohoo!

**Comment by gurrhack** [comment]
Yes. I am going to give the artists a chance to update the tilesets first though

**Comment by pftbest** [comment]
do you know any new monsters(objects) that were added in 3.6.0?

**Comment by gurrhack** [comment]
No new monsters

**Comment by pftbest** [comment]
than it means that there is no need to update tilesets, right?

**Comment by gurrhack** [comment]
There are a few new food items and dungeon features

**Comment by TPS** [comment]
When should we expect APK release?

**Comment by gurrhack** [comment]
Within a couple of days is the plan
