### ISSUE TITLE
NetHack 3.6.0 menu bar not saving changes.

### ISSUE THREAD

**Issue by summonthethunder** [gurrhack/NetHack-Android#17]
NetHack 3.6.0 port menu bar at the bottom of the screen not saving any changes made it, to include adding or changing commands.  Happens upon new game or loading a saved game (when it loads, see separate issue).  Droid Maxx, Android 4.4.4.

I changed commands via pushing and holding the command panel to make changes, then saved. Reloaded, and command panel reverts to standard command panel without my changes. Next, tried setting up new commands via the Command Panel option in the Settings menu, renaming Panel 2 to Command Panel, activating for both portrait and landscape mode. I also remembered to disable portrait and landscape mode for the Standard Panel set. Saved, then reloaded, and got the same result of all commands reverting to initial setup, ignoring changes.

**Comment by gurrhack** [comment]
That is very strange. Are any other settings reverted?

**Comment by summonthethunder** [comment]
No other changes in settings have changed that I can see.

Just tried it again, same issue.  Here are the particulars (all changed by push-holding the command panel):

- set up a game in wizmode for testing.
- changed 'F' command in panel to '^f'.
- removed 'menu' command.
- moved position of 'a' and 'D' commands from end of panel to beginning.
- added '^i' command at beginning.

Tested the commands themselves and they work fine.  Saved, the reloaded.  All commands revert, but 'menu' command remains removed.

Next set of particulars are same as above, but all changes made via the Panel 2 settings in the Command Panel settings option, deactivating portrait/landscape for Standard Panel and activating them for Panel 2.  Same result.

Is there a pointer in the code not looking at user definitions and staying at ROM instead?

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


That is very strange. Are any other settings reverted?

-

**Comment by summonthethunder** [comment]
Hello Martin,

How goes the debugging?

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


That is very strange. Are any other settings reverted?

-

**Comment by summonthethunder** [comment]
Some further info...

Wife's Android tablet running 6.0.1 is showing the same symptoms as Android 4.4.

On a whim, tried the 1.4.0 version of your app and your current UnNetHack app, and the command panel works perfectly on both.

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


That is very strange. Are any other settings reverted?

-

**Comment by gurrhack** [comment]
Not entirely sure what's happening there. I fixed an issue with wizard commands disappearing. You can find a new release here https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.0-3 and  on Google Play in a while

**Comment by summonthethunder** [comment]
Ok I'll check it out.  Thanks for your work!

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Not entirely sure what's happening there. I fixed an issue with wizard commands disappearing. You can find a new release here https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.0-3 and on Google Play in a while

-

**Comment by summonthethunder** [comment]
Martin,

Did some extensive testing in normal and wizard modes, and the command panel seems to be working great now!  Nothing else wrong I can see.

Jared

Sent from my Verizon Wireless 4G LTE DROID


Martin Gustafsson <notifications@github.com> wrote:


Not entirely sure what's happening there. I fixed an issue with wizard commands disappearing. You can find a new release here https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.0-3 and on Google Play in a while

-
