### ISSUE TITLE
Suggestion: wrap status in portrait layout

### ISSUE THREAD

**Issue by CJBrew** [gurrhack/NetHack-Android#18]
Is there a way the status bar could be made to wrap, particularly in portrait mode?

Important things at the end, like hunger status etc. get lost off the edge of the screen.

**Comment by gurrhack** [comment]
It's wrapping for me. Which version of nethack are you running? Also what Android version and phone model do you have?

**Comment by CJBrew** [comment]
It seems to be a particular problem if I have a command panel there. See attached.

![screenshot_2016-01-01-22-07-02](https://cloud.githubusercontent.com/assets/992038/12072398/686212ac-b0d4-11e5-8e44-75c34f334579.png)


I'm using a Note 4, Android 5.1.1, the latest build of Nethack.

**Comment by gurrhack** [comment]
Fixed
