### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by sdreher-techfak** [gurrhack/NetHack-Android#20]
Since the update to 3.6.0 the game usually freezes after a couple of clicks.
I haven't found out what triggers it, but often it happens when I try to open the menu.
I am using a Samsung GALAXY S4 mini.
Also, I haven't had these problems on this phone before the update.

**Comment by gurrhack** [comment]
Can you try the latest release from this site and see if it still happens?
https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.0-2

**Comment by sdreher-techfak** [comment]
That works, thanks.
