### ISSUE TITLE
Wizzard Attack

### ISSUE THREAD

**Issue by mueer01** [gurrhack/NetHack-Android#24]
Hi Martin,

it was the first time in 25 years(!) of nethacking, that the WoY attacked me as soon as I entered his level.
Usually he is sitting in his cage in the middle of this level and does not move, as long as I do not attack him.
Is this a bug or did someone change the rules of the game?
I think it's a bad idea.
1. no need to conquer the cage anymore (because he comes out on his own).
2. no time to prepare the long way down- and upstairs anymore.

Regards,
Erhard

**Comment by gurrhack** [comment]
Hi Erhard,

That effect has been limited in the NetHack source repository: https://sourceforge.net/p/nethack/NetHack/ci/04bc048073e87c55e3bcfa3fceab44fe86361e8a/

Keep in mind that this is just an unofficial port for Android and I'm not associated with the development of NetHack in general, but as soon as a new NetHack version is released I will update this port.

// Martin
