### ISSUE TITLE
Crash on turn undead (shopkeepers)

### ISSUE THREAD

**Issue by CJBrew** [gurrhack/NetHack-Android#25]
I have reproduced this a couple of times in Wizard mode, but I don't know in how many situations it occurs.

Method:
1) Find a shop
2) Get a wand of turn undead
3) Use a means of monster creation to create something that will kill the shopkeeper (a pet archon is an ideal candidate)
4) Let the archon kill the shopkeeper
4a) repeat steps 1-4 until it leaves a corpse
5) Zap the corpse with turn undead ***Game crashes***

It's a bit of a pain to reproduce, partly because I don't know a way to force the game to create shops (I know there are command line options for this, but through the Android port?), and it seems fairly unusual for the murder to leave a corpse. 

Can anyone else reproduce the bug?

**Comment by SunnyEric** [comment]
My test is that when you kill the shopkeeper(any way) in Wizard mode, then zap the wand of turn undead to shopkeeper's corpse, the game will crash.

**Comment by gurrhack** [comment]
I can reproduce this with the 3.6.0 release on linux too. I'll check if they've fixed it in the development version.

**Comment by gurrhack** [comment]
It's not fixed in the latest sources and I've forwarded a bug report to the devteam.
I don't find it critical enough to warrant an immediate fix for the Android port, so I'm closing this.

**Comment by CJBrew** [comment]
Hadn't thought it would be a bug in the NetHack core! To be fair, it's a slightly odd thing to do, but that's how we find bugs (by doing odd things).

Thanks, guys.

**Comment by gurrhack** [comment]
FYI this has now been fixed in the NetHack repository: https://sourceforge.net/p/nethack/NetHack/ci/24400cdca458adc6dea2a84ca557538fdd096830/

**Comment by CJBrew** [comment]
To be fair, I don't know why I was doing this in the first place. Any sane
person would leave the shopkeeper dead!

Glad the bug is fixed; is there a merge path back to Gurrhack?

**Comment by gurrhack** [comment]
I'll merge it eventually. I'd rather wait until the next official NetHack release though, unless it takes too long.
