### ISSUE TITLE
Access to WIZKIT denied when attempting to make a new character in Wizard Mode

### ISSUE THREAD

**Issue by summonthethunder** [gurrhack/NetHack-Android#27]
I have created a wizkit.txt file in com.tdb.Nethack and filled it out as per nethackwiki.com wizkit page, but when i load a character up in wizard mode, i get a message saying "access to wizkit.txt denied (2)".  Game then loads with a normal inventory loadout as per role.

**Comment by gurrhack** [comment]
It works for me. That error number (2) indicates that the file doesn't exist. Are you sure you spelled it correctly?

**Comment by summonthethunder** [comment]
It was spelled correctly.  Problem is, my chosen text editor was not saving as .txt, for whatever reason.  That will be corrected.  Thank you for your help.  Please flag this as corrected.

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Aug 20, 2016 at 3:11 AM -0700, "Martin Gustafsson" <notifications@github.com<mailto:notifications@github.com>> wrote:


It works for me. That error number (2) indicates that the file doesn't exist. Are you sure you spelled it correctly?

-
