### ISSUE TITLE
Directional buttons occasionally misfire

### ISSUE THREAD

**Issue by CJBrew** [gurrhack/NetHack-Android#28]
There is a good chance this is down to my fat fingers, but I've been careful and still seen it happen reasonably often. It'd be nice to know it wasn't just me...

I've no idea why this might happen. Symptom is when attacking left with either Zap (z or Z) or Fire f/ throw, usually in a corridor. Particularly when your pet is on your right, you may inadvertently attack the pet. 

If this is a bug, I suspect it's related to how the touchscreen logic detects the position of the directional button overlay. 

Under some conditions the overlay moves left (such that the old "left" position can be approximately the new "right"), and I wonder whether the touch detection logic is always in sync with the display.

Using a Galaxy Note 4. I can provide more info if necessary.

**Comment by gurrhack** [comment]
What are the conditions in which the overlay moves left? It's not supposed to move.
What are your settings for the directional overlay?

**Comment by CJBrew** [comment]
I can't seem to post an image, at least from my phone. I so I'll describe.. 

I have custom command panels left and right, and the directional pad sits just on the left of the right side command panel, in the bottom right.

When certain messages pop up, the command panels are hidden, and directional overlay moves right to the edge of the screen, into the vacated space.

**Comment by gurrhack** [comment]
Ah, I see. I'll try to reproduce the problem. Do you have the "Allow map input with overlay" option enabled?

**Comment by CJBrew** [comment]
Ah... Yes, I do. Perhaps that's what's happening!...

**Comment by CJBrew** [comment]
Closing this as it seems to be user error or resolved.
