### ISSUE TITLE
Feature request : configurable command button size 

### ISSUE THREAD

**Issue by CJBrew** [gurrhack/NetHack-Android#32]
The command buttons seem really small on my 10" android tablet. It would be great to be able to increase the size of them.

**Comment by gurrhack** [comment]
I'll see what I can do.

**Comment by CJBrew** [comment]
Thanks!

For what it's worth, the game looks beautiful on my Galaxy Tab 1, it's just a bit tricky hitting the right button sometimes.

**Comment by gurrhack** [comment]
How about something like this?

![screenshot_20170909-150751](https://user-images.githubusercontent.com/7879374/30240450-f41edd98-9570-11e7-9624-de36986d6bd8.png)

**Comment by CJBrew** [comment]
So, you can set a button size for individual panels, or all buttons, or even individual buttons? 

I think that's probably the sort of thing though! That way I can set the most commonly used buttons to be more accessible.

**Comment by gurrhack** [comment]
You can only set the size for individual panels now, and the d-pad overlay. I've changed the dialog a bit since that screenshot. It can be extended to individual buttons later if it's needed.

**Comment by CJBrew** [comment]
I am sure individual buttons isn't necessary. There'll be plenty of flexibility via different command panels.

**Comment by gurrhack** [comment]
Fixed.
