### ISSUE TITLE
Building on recent NDK

### ISSUE THREAD

**Issue by Ranbato** [gurrhack/NetHack-Android#34]
It looks like a few things need to be changed to compile this with a recent NDK as I keep getting errors.
Researching a bit, it looks like the [Unified Headers](https://android.googlesource.com/platform/ndk/+/master/docs/UnifiedHeaders.md) and deprecation of gcc are the issues.

Anyone resolved this yet?  If not I'll play with it and see what I can figure out.

**Comment by gurrhack** [comment]
Yes, you can build it with NDK r16b by creating a standalone toolchain (build/tools/make-standalone-toolchain.sh) using --arch=arm --install-dir=somedir.
Then point sysroot in Makefile.src to somedir/sysroot and replace gcc with clang.

I'll commit updated build scripts eventually.

**Comment by gurrhack** [comment]
Fixed. Updated build instruction and updated makefile.
