### ISSUE TITLE
Upgrade to 3.6.1

### ISSUE THREAD

**Issue by tmp6154** [gurrhack/NetHack-Android#36]
Woo-hoo! This has finally happened, NetHack 3.6.1 is released.

http://nethack.org/v361/release.html

**Comment by tek909** [comment]
Any new tiles for nethack or unnethack?

**Comment by tmp6154** [comment]
No, there's no new tiles in 3.6.1.

**Comment by tmp6154** [comment]
3.6.1 introduces a new option that could be of use in windowport.

> herecmd_menu
> 
> When using a windowport that supports mouse and clicking on yourself or next to you, show a menu of possible actions for the location. Same as herecmdmenu and therecmdmenu commands.

**Comment by gurrhack** [comment]
That option will be supported, but not turned on by default.

**Comment by gurrhack** [comment]
Fixed. [Release 3.6.1](//github.com/gurrhack/NetHack-Android/releases/tag/3.6.1)
