### ISSUE TITLE
# menu contains Wizard mode options

### ISSUE THREAD

**Issue by CJBrew** [gurrhack/NetHack-Android#37]
The # extended menu in the 3.6.1 release appears to contain many items that I think we shouldn't be seeing in normal mode (I.e. Only as "Wizard" mode). E.g. Lightsources, wiz* (inc. Wizsmell), and others -- and things that shouldn't be in that menu as they're controlled by regular keyboard commands (e.g. "drop").

For example, this is very annoying when trying to #pray... 

Perhaps this menu may be the same in vanilla 3.6.1, I've not checked.

**Comment by gurrhack** [comment]
Fixed in 11a590b88c28342c9261e47c9dc49ffe858457cc (I typed wrong issue number in commit message)
