### ISSUE TITLE
MENUCOLOR makes an item unusable

### ISSUE THREAD

**Issue by goodnewz** [gurrhack/NetHack-Android#39]
I have in my nethack options file the following two lines:
```
#  Show all blessed items in green
MENUCOLOR=" blessed "=green&bold

#  Show all cursed items in red
MENUCOLOR=" cursed "=red&bold
```
When I name an item ``` cursed ``` or identify a cursed item, menucolor kicks, however there is a bug in the popup menu where the items becomes unselectable. 

see the following two screenshots I took:

![test1](https://user-images.githubusercontent.com/25808527/40882463-9e478f2a-66b0-11e8-9c82-2b63b842cbb6.png)
![test2](https://user-images.githubusercontent.com/25808527/40882464-a0986484-66b0-11e8-833c-27488c5ecfad.png)

The short sword in the example above becomes undroppable. You cannot select using the menu or by letter. You can however swap it with ```x```. 

I have not experienced this specific issues on the windows port, so it must be an android specific bug.

**Comment by gurrhack** [comment]
Weird. But I can reproduce it so it should be easy to fix.

**Comment by gurrhack** [comment]
Fixed
