### ISSUE TITLE
Status background opacity doesn't apply at start

### ISSUE THREAD

**Issue by Kamjue** [gurrhack/NetHack-Android#41]
The **"Status background opacity"** value saves correctly, but it doesn't applies at the app's start.

![image00002](https://user-images.githubusercontent.com/6945219/40953849-95596dca-684f-11e8-8f41-3d5a15302a6e.png)

It has to be applied manually by opening it's menu and just tapping **"OK"**.

![image00001](https://user-images.githubusercontent.com/6945219/40953855-9c935ea2-684f-11e8-8180-c3af73c4e0f6.png)

Then it applies correctly.

Tested in:

- Motorola Moto X using CM 13.
- Samsung S3 Mini using CM 11.
- Pegatron Chagall tablet using stock Android 4.1.1.

**Comment by gurrhack** [comment]
Fixed
