### ISSUE TITLE
Upgrade to 3.6.2

### ISSUE THREAD

**Issue by tmp6154** [gurrhack/NetHack-Android#46]
Today, a NetHack 3.6.2 was officially released by the DevTeam.

**Comment by gurrhack** [comment]
Nice! I'll probably make a pre-release this weekend.

**Comment by gurrhack** [comment]
[There](https://github.com/gurrhack/NetHack-Android/releases/tag/3.6.2b)

**Comment by tmp6154** [comment]
Great! Will test it.

**Comment by tmp6154** [comment]
Not yet sure, if it's a new bug, or whether it might have something to do with continuing an existing 3.6.1 save, so I've decided not to open a separate issue and report there.

I've attempted to force locked large box with my healer, wielding a scalpel. When I center-pressed on the touchscreen, it didn't suggest to force lock, just to loot. But of course, it's failed, because it locked. I was only able to force it by explicitly opening a keyboard and typing Meta-F. It then opened force lock dialog. But after that, touch screen movement has stopped to work. Touching anywhere on screen didn't work. I was able to fix this by typing Meta-L. Then loot dialog opened up, I've looted the contents of box and touchscreen movement started to work again.

**Comment by gurrhack** [comment]
I seem to have lost a few Android specific features during the merge with 3.6.2. "Auto force" is one of them. There's also a numberpad bug that has reappeared, causing the game to use the letter 'l' (move right) for loot instead of M-L. Maybe that's related to how you got "stuck"?

**Comment by tmp6154** [comment]
Yes, that's probably related to the loot bug. I can assume that game was, possibly, waiting for loot confirmation response, but Android dialog didn't pop up for some reason and movement input went nowhere instead.

**Comment by gurrhack** [comment]
[Patched version](https://github.com/gurrhack/NetHack-Android/releases/tag/3.6.2c)

**Comment by gurrhack** [comment]
Fixed.
