### ISSUE TITLE
On-screen keyboard: shift doesn't stack with Meta.

### ISSUE THREAD

**Issue by tmp6154** [gurrhack/NetHack-Android#47]
It's possible to add an extended command onto panel (such as M-A, which would do annotate), but it doesn't seem to be possible by opening on-screen keyboard. You can touch Shift (and it will even light up), but if you touch Meta - it will open a set of lowercase commands, e.g. M-a (which is adjust)), even though Shift is active, so that makes it impossible to type extended commands that require both Shift+Alt from on-screen keyboard.

There's a few such commands, and some have alternative ways to invoke (besides extended command menu), but particularly annotate, conduct, tip and ride cannot be invoked through on-screen keyboard.

https://nethackwiki.com/wiki/Commands

**Comment by gurrhack** [comment]
Oh, I didn't realize they've added upper case Alt commands. Since there are only four of them, maybe I can squeeze them all in on the same page.
The next step would be to add full support for custom key bindings.

**Comment by gurrhack** [comment]
Fixed
