### ISSUE TITLE
Update to 3.6.6

### ISSUE THREAD

**Issue by TideGear** [gurrhack/NetHack-Android#54]

**Comment by TideGear** [comment]
A gurrhack's work is never done. (Thank you!)

**Comment by gurrhack** [comment]
Fixed.

[v3.6.4](https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.4)
[v3.6.5](https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.5)
[v3.6.6](https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.6)
