### ISSUE TITLE
Adding discoveries command to panel doesn't stick

### ISSUE THREAD

**Issue by HairyDude** [gurrhack/NetHack-Android#55]
By long pressing on a command button, you can add a button for the discoveries command (`\`). This works, but when you save and quit and later restore, the button is gone and the following button has gained a couple of leading spaces.

It's also not possible to add such a button via the menu.

**Comment by gurrhack** [comment]
Fixed in [v3.6.6-1](https://github.com/gurrhack/NetHack-Android/releases/tag/v3.6.6-1)
