### ISSUE TITLE
Hearse support

### ISSUE THREAD

**Issue by Ranbato** [gurrhack/NetHack-Android#6]
Any chance of porting the Hearse support from the iOS version?

The Hearse code is available at https://github.com/dirkz/iNetHack/tree/master/Classes . It is in Obj-C, but really the process shouldn't be too complicated.

Thanks,
Ranbato

**Comment by Ranbato** [comment]
All of the Hearse code is working and I haven't seen any issues recently
though I'm sure there are some edge cases where it will quietly do
something wrong  :)

I have read through all of the UI and IO classes and I think I'll
restructure my code just a bit so that I can model the UI portion after the
Tileset code you have.  I think that will provide for a better user
experience with just a single Hearse option in the main screen and the
Hearse settings is a separate popup.



On Tue, Dec 30, 2014 at 2:29 AM, gurrhack <notifications@github.com> wrote:

> Yeah, on startup is probably better in that case.
>
> I've also used the Toast class to show notifications within NetHack. That
> could work for Hearse too, just make sure to run them on the main thread.
> You can use a Handler for that (see NetHackIO for example)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gurrhack/NetHack-Android/issues/6#issuecomment-68341677>
> .
>



-- 
Disclaimer:
By sending an email to ANY of my email addresses you are agreeing that:

   1. I am by definition, "the intended recipient"
   2. All information in the email is mine to do with as I see fit and make
such financial profit, political mileage, or good joke as it lends itself
to. In particular, I may post it to the internet.
   3. I will take the contents as representing the views of your company.
   4. This overrides any disclaimer or statement of confidentiality that
may be included on your message.

**Comment by gurrhack** [comment]
By the way. You can send me a diff whenever you feel like it, or create a pull request. It might take a while until I can do a thorough review&testing though

**Comment by Ranbato** [comment]
Here is a functioning patch.  Everything is working just fewer bells and
whistles than I wanted.

I gave up temporarily on the fancy preferences because it was taking too
long and life is busy. :)



On Thu, Jan 8, 2015 at 4:21 PM, gurrhack <notifications@github.com> wrote:

> By the way. You can send me a diff whenever you feel like it, or create a
> pull request. It might take a while until I can do a thorough
> review&testing though
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gurrhack/NetHack-Android/issues/6#issuecomment-69268571>
> .
>



-- 
Disclaimer:
By sending an email to ANY of my email addresses you are agreeing that:

   1. I am by definition, "the intended recipient"
   2. All information in the email is mine to do with as I see fit and make
such financial profit, political mileage, or good joke as it lends itself
to. In particular, I may post it to the internet.
   3. I will take the contents as representing the views of your company.
   4. This overrides any disclaimer or statement of confidentiality that
may be included on your message.

**Comment by gurrhack** [comment]
I've uploaded a test release with the Hearse implementation
https://github.com/gurrhack/NetHack-Android/releases/tag/v1.3.7b

**Comment by gurrhack** [comment]
Fixed.
